_BASE_: "../base-prompt_changed_P_VK.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: "CUB"
  DATAPATH: "/projectnb/ivc-ml/ssjoshi/adversarial/E2VPT/data/fgvc/CUB_200_2011"  #TODO: need to specify here
  NUMBER_CLASSES: 200
  MULTILABEL: False
MODEL:
  TYPE: "vit"
SOLVER:
  LOSS: "softmax"
  BASE_LR: 0.1
  WEIGHT_DECAY: 0.01
