_BASE_: "../../../base-prompt_changed_P_VK_ssl_mae.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: "StanfordCars"
  DATAPATH: "/home/shaunak_joshi/thesis/E2VPT/data/fgvc/Stanford-cars"  #TODO: need to specify here
  NUMBER_CLASSES: 196
  MULTILABEL: False
MODEL:
  TYPE: "ssl-vit"
SOLVER:
  LOSS: "negative_ce"
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.001
