_BASE_: "../base-prompt_changed_P_VK_ssl_mae.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: "CUB"
  DATAPATH: "home/shaunak_joshi/thesis/E2VPT/data/CUB_200_2011"  #TODO: need to specify here
  NUMBER_CLASSES: 200
  MULTILABEL: False
MODEL:
  TYPE: "ssl-vit"
SOLVER:
  LOSS: "negative_ce"
  BASE_LR: 0.1
  WEIGHT_DECAY: 0.01
